### ISSUE TITLE
Proposed rewording of 

### ISSUE THREAD

**Issue by mjohn706** [openxc/reference-vi#10]
The opening paragraph reads:

OpenXC is an API to your car - by installing a small hardware module to read and translate metrics from a car's internal network, the data becomes accessible from most Android applications using the OpenXC library. You can start making vehicle-aware applications that have better interfaces based on context, can minimize distraction while driving, are integrated with other connected services, and can offer you more insight into your car's operation. This website is the documentation for a reference design of an OpenXC-compatible Vehicle Interface - for more information on the platform in general, visit openxcplatform.com.

I propose the rewording:

OpenXC is an API to your car - by installing a small hardware module to read and translate metrics from the car's internal network (CAN), the data becomes accessible from most Android applications using the OpenXC library. Using this library you can start making vehicle-aware applications that offer improved context-based interfaces, minimize distraction while driving, integrate with other connected services, and  offer you more insight into your car's operation. This website is the documentation for a reference design of an OpenXC-compatible Vehicle Interface - for more information on the platform in general, visit openxcplatform.com.

The main benefit of this proposed rewording is that it is now clear that the same network is being referred to in both places, but there are other small benefits, too.

**Comment by peplin** [comment]
Looks good, you can just make the change directly. Thanks Matthew!
