### ISSUE TITLE
OpenXC-VI vehicle-interface.bom.xls no information for OBD-II connector

### ISSUE THREAD

**Issue by tangchihwei** [openxc/reference-vi#28]
The bom is incomplete in that it doesn't provide the OBD-II connector link.

**Comment by zacnelson** [comment]
hey @tangchihwei I found this link in an old version of the BOM document. I can push a change that includes it. Not sure if this is the exact part used in the production run. 

http://www.cct-elec.com/sdp/213844/4/pd-955932/10065677-2539664/OBDII_16P_MRight_Angle_CONNECTOR.html

**Comment by zacnelson** [comment]
Fixed here: https://github.com/openxc/reference-vi/commit/b2582e0b350b7cbcc5db5ef8484ea58985574bed

@tangchihwei if you check with the manufacturing and that's the wrong link, then we can re-open the issue.
