### ISSUE TITLE
Clarify in "Programming" section about firmware.bin

### ISSUE THREAD

**Issue by zacnelson** [openxc/reference-vi#29]
Clarify that when flashing new firmware, the firmware.bin file that appears in Windows Explorer or Finder is not the flashed firmware. It's a placeholder. Don't worry about the name "firmware.bin" mismatching any previously flashed firmware versions.

What should the wording be? 

"The firmware.bin filename is just a placeholder. To check if your firmware is properly flashed, plug in the VI via USB and try running `openxc-control version` from the command line."

**Comment by peplin** [comment]
I like your wording - there's a more technical description in the [bootloader docs](https://github.com/openxc/openlpc-USB_Bootloader#flashing-user-code):

> Note that the firmware.bin file will always look the same (with an old modification date and the same firmware.bin filename), even if you reflash and remount the bootloader. It's not a true filesystem, we are just creating a fake file so you can write to it from standard file browser tools.

**Comment by zacnelson** [comment]
We could do a link within the wording to the bootloader docs you just mentioned. 

"The firmware.bin filename is [just a placeholder](https://github.com/openxc/openlpc-USB_Bootloader#flashing-user-code). To check if your firmware is properly flashed, plug in the VI via USB and try running `openxc-control version` from the command line to get the firmware version."

**Comment by peplin** [comment]
Looks good to me, go ahead and make the change

**Comment by zacnelson** [comment]
Updated Mac and Windows programming.

20df210d
